# The scientific process

> *There is something fascinating about science. One gets such a
> wholesale return of conjecture out of a trifling investment of fact.*
>
> Mark Twain
>
> *To do science is to search for patterns, not simply to accumulate
> facts.*
>
> Robert MacArthur

## Stages in the scientific process {#stages-scientific-process}

Science is about asking, and answering, the right questions. Within this process a number of distinct stages usually occur: making observations, asking questions, formulating hypotheses, and testing predictions. Collectively these are the building blocks of what is known as the scientific method. Exactly how they fit together, and what the philosophical and practical limitations of different approaches are, have been the subject of much debate by philosophers of science. We are not going to tackle those issues here, fascinating though they are, but instead try to extract a general working framework for the process of a typical scientific investigation.

### Observations {#stages-observations}

**Observation** — *information, or impression, about events or objects*.

In general the questions we ask are not generated by pure abstract thought, but are a result of observations about the natural world. These may take the form of direct observations we make ourselves, patterns that crop up in data collected for other purposes, in non-specific surveys, and the previous work, or accumulated information, of other people.

So, while pottering around in a stream one day, you notice that the freshwater ‘shrimps’ (*Gammarus*) that abound in the stream seem to occur almost entirely under stones; you rarely seem to see them when you just watch a patch of open stream bed. Having made observations, it may be necessary to collect some more data to check that this phenomenon is not just a one-off event, or a false impression. Look under a few more
stones, watch the same species another day, or in another place, check the literature for similar observations by others.

Such observations of biological systems will lead almost automatically into asking questions.

### Questions {#stages-questions}

**Question** — *what it is that you want to know; the scope of your investigation*.

e.g., Why does *Gammarus* spend most of its time under stones?

You should try and make your question reasonably focused - the overall aim of your study is to answer this question. The question of why the tropics are more diverse than the temperate regions is a vast topic - so
even though it is a valid (and fascinating) question, it may not be a good choice for a final year project or even a PhD!

The next stage is to formulate an hypothesis.

### Hypotheses {#stages-hypotheses}

**Hypothesis** — *an explanation proposed to account for observed facts.*

In general, in biology, the important distinguishing feature of an hypothesis is that it specifies some biological process, or processes, which might account for the observations made. One question will often
generate more than one hypothesis:

*Gammarus* occur under stones because:

-   they need to shelter from the current

-   their food (leaf litter) gets trapped and accumulates under stones

-   they are subject to predation by visually hunting fish and need to remain out of sight

Formulating hypotheses requires more than just a restatement of the question - it usually embodies some mechanism (though in some cases this may not be fully understood) and it will often draw on additional information (e.g., the fact that *Gammarus* feed on dead leaves).

### Predictions {#stages-predictions}

**Prediction** — *what you would expect to see if the hypothesis was true*.

Hypotheses are about proposing explanations, but they might not be directly testable; that is they may not tell you what data to collect, or what pattern to expect in the data. To be able to test an hypothesis you need to make some predictions from that hypothesis. These will be determined both by what you expect to see and what it is possible, or practical, to measure. A prediction is not simply a rephrasing of the hypothesis - it should more or less give you a statement of the experiment to conduct or observation to make, and type of data to
collect:

-   *Shelter hypothesis:* a greater proportion of *Gammarus* should be
found in the open in streams with slow flow, or in slower flowing
areas of a stream.

-   *Food hypothesis:* *Gammarus* should not aggregate under stones from
which all leaf litter has been removed; *Gammarus* should aggregate
on patches of leaf litter tethered in the open part of the stream
bed.

-   *Predation hypothesis:* *Gammarus* should aggregate under stones
more in streams where fish are present than where they are not;
*Gammarus* may spend less time under stones at night.

Ideally you are looking for a prediction that is unique to the hypothesis it is based on - so if the prediction is true only one of the hypotheses could have been responsible, but this may not always be possible and some combination of predictions may need to be used. Additionally, several processes may be operating at the same time. This makes hypothesis testing harder still. It may be necessary to consider two or more hypotheses, and their corresponding predictions, in combination. For example, *Gammarus* may be under stones because it prefers the sheltered environment, but also because food accumulates there. In this case we might expect that *Gammarus* will show a weak aggregative response to shelter alone, or food alone, and a stronger one
to them both together.

## Hypothesis testing

Once we have firmed up our questions, hypotheses, and predictions we can collect the data to evaluate our ideas. On the basis of these data we will either accept or reject the various hypotheses. The important thing to realise about the process of hypothesis testing is that, in science especially, hypotheses are either rejected, or not rejected, but an hypothesis can rarely, except in trivial cases, be proved.

This seems like an odd state of affairs! True, but it does make sense. Since you cannot be sure that you have thought of all the possible hypotheses to explain an observation, finding evidence that supports the prediction from one of your hypotheses, does not guarantee that the hypothesis is the only one which could have produced the effect you find. On the other hand, if you find evidence that directly contradicts the prediction(s) from your hypothesis, you can be certain (assuming the prediction and data are not flawed) that the hypothesis cannot be true.

An hypothesis which predicted that all conifers should be evergreen could be supported by numerous observations of different conifer species in forests around the world, but is conclusively refuted by the first larch tree we encounter.

Having tested your hypothesis, by examining the evidence that its predictions are true, you may accept it as the best (so far) explanation of the observations, or you may reject it as an explanation, and turn to other hypotheses. The same procedure must then be repeated for these hypotheses.

This basic cycle of proposing hypotheses and then seeking evidence potentially capable of falsifying them, is, in essence, the idealized model of the scientific process famously proposed by the philosopher of science Karl Popper (1902-1994). It is often termed *falsificationism*.

## Don’t we ever know anything for sure? {#are-we-sure}

The method presented here provides a view of science as one in which we suggest hypotheses, then test them, trying to reject them by finding conclusive counter-evidence, then replacing them with new hypotheses. It all sounds a bit frustrating. In fact of course we do ‘accept’ hypotheses all the time — that is we fail to reject them over and over again. These hypotheses become more accepted and in some sense become regarded as ‘true’ if repeated attempts to test them all fail to provide good counter evidence. In other words, we have some ideas that are doing pretty well in terms of resisting falsification, and we use these as our best estimates of the truth, with the proviso that it is still possible a better idea will come along in due course.

The simple process of falsification described above also presents a picture of scientists as wonderfully neutral, objective creatures, rationally proceeding through cycles of setting up hypotheses, testing them, rejecting them, cheerfully setting them aside and starting over again. Of course this is not a true reflection of the complex, often messy, business really involved in trying to figure out how the world works. Philosophers of science have argued long and hard about how far from this idealized process real science actually is. Various alternative philosophies suggest more ‘realistic’ processes, such as Thomas Kuhn’s view of science as periods of relative stasis, where people work within an accepted paradigm (a set of views about how things work) despite accumulating evidence that doesn’t always support the paradigm, until finally it is upset by a ‘revolution’ which rejects the entire paradigm, and proposes a new view. The philosopher Imre Lakatos proposed some resolution of these views, suggesting that scientific ideas were grouped together in ‘research programmes’ concerned with particular endeavours, and that within these there may be core ideas that are not challenged, but other related ideas which are being challenged and adjusted by falsification, and that together these make each research programme progress. Programmes that don’t progress should be abandoned in favour of those that do.

Of course that is a very over-simplified sketch of some important ideas, which are well worth reading a bit about, but in practice these philosophical arguments are really more focused on how whole areas of science develop. When you are just thinking about constructing a simple study of one problem, then the basic falsification cycle is a pretty good approach to have in your mind. Even in its simple form, however, it is not immune from the effect of human fallibility (see below).

The process laid out here is not a strict set of rules, but outlines an approach to scientific investigation which is widely considered to provide a rigorous and productive system. As with all such systems understanding the ‘normal’ process is a prerequisite for constructively breaking the rules.

```{block, type='advanced-box'}
**It's hard to reject an hypothesis you love!**

An interesting aside on the process is given by Sutherland (1994) who suggests that, in everyday life at least, we are often very reluctant to deliberately seek evidence that might refute a hypothesis we have formulated, and often persist in holding on to the hypothesis even when the evidence is against us.  This can be seen in experiments where people are presented with a sequence of numbers (say 2, 4, 6) and have to try and establish the general rule to which the set of numbers conforms.  The subject decides on an initial rule and then can test this rule by suggesting other sets of numbers and being told whether or not those numbers conform to the rule. 

The initial guess at a rule is usually 'even numbers in ascending order', and the initial test suggestions are typically another set of even numbers ascending by two  (e.g. 16, 18, 20). These, the subjects are told, conform to the rule.  The next set of numbers suggested is then often another similar set (40, 42, 44) -- which again conforms, and sometimes another similar guess will follow. However, the suggestion of further sets of even numbers ascending by two cannot test this (most simple rules that allow 2, 4, 6 will allow the other sequences too). A better first suggestion would be to change one of the components of the initially proposed rule e.g. even numbers to odd numbers: 3, 5, 7;  or the increment:  2, 8, 14.  If these conform we can reject a specific component of our initial rule. (The rule is, in fact, simply any ascending sequence of numbers.)
```

## Further reading {#further-reading}

Barnard C, Gilbert F and McGregor P (1993) *Asking questions in biology*. Longman.

Ladyman, J (2002) *Understanding the philosophy of science*. Routledge.

Sutherland S (1994) *Irrationality*. Penguin.
